### ISSUE TITLE
Configuration Example? 

### ISSUE THREAD

**Issue by KWLandry** [ec2604/import_anywhere#1]
Would you mind putting an example of configuring the IMPORT_ANYWHERE_DIRS env var in the Readme? Hopefully for the directory structure you have in the Readme file. I'd like to take advantage of this work but without some info as to what the var should look like, am faced with working it out and could use a break in the time it takes to do anything with Python, thanks,

**Comment by ec2604** [comment]
It's actually explained at the bottom of the README, you need to place the dirs you want in the  IMPORT_ANYWHERE_DIRS environment variable. For example in Linux in the terminal, export IMPORT_ANYWHERE_DIRS=".../MY_PARENT_FOLDER/PACKAGE_A"
